# -*- coding: utf-8 -*-
"""frame_from_picam

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsSEqBtjY6zezxVchJFmjaiaUbpw7pwE
"""

# After installing OpenCV for the raspberry Pi as described at
# https://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/
# the below script will allow you to pull a frame from the video stream, which you can pass into 
# the classification model you have built using the fast.ai code

#source: 
#https://picamera.readthedocs.io/en/release-1.10/recipes1.html

import io
import time
import picamera
import cv2
import numpy as np

# Create the in-memory stream
stream = io.BytesIO()
with picamera.PiCamera() as camera:
    camera.start_preview()
    time.sleep(2)
    camera.capture(stream, format='jpeg')
# Construct a numpy array from the stream
data = np.fromstring(stream.getvalue(), dtype=np.uint8)
# "Decode" the image from the array, preserving colour
image = cv2.imdecode(data, 1)
# OpenCV returns an array with data in BGR order. If you want RGB instead
# use the following...
image = image[:, :, ::-1]

